---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    attributes:
      common:
        environment:
          name: "test"
    run_list:
      - recipe[chef_common_utils::default]
